spring.application.name=takeHomeChallenge
server.port=8085
server.error.include-message=always

# ========== DATASOURCE (H2) =========
spring.datasource.url=jdbc:h2:mem:devdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========= JPA / HIBERNATE =========
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate=warn
logging.level.org.hibernate.orm.connections.pooling=error
logging.level.org.hibernate.SQL=off

# ======= SECURITY =====
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=3600000

